
package com.emagic.vista;

import com.emagic.modelo.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class JFrameAhorcado extends javax.swing.JFrame {

    private Muñeco muñeco;
    private Palabra palabra;
    private Marcador marcador;

    
    public JFrameAhorcado() {
        initComponents();
        
        
        
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/com/emagic/gfx/tux.gif"));
        this.setIconImage(img.getImage());
        this.setMinimumSize(new java.awt.Dimension(600,500));
        jTextFieldLetra.setEnabled(false);
        jLabelMuñeco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelPalabra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLetra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelIntentos = new javax.swing.JLabel();
        jLabelAciertos = new javax.swing.JLabel();
        jLabelFallos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelMuñeco = new javax.swing.JLabel();
        jLabelMuñeco1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAcerdaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El juego del Ahorcado");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Palabra"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelPalabra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPalabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPalabra.setText("????");
        jLabelPalabra.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelPalabra, gridBagConstraints);

        jLabel1.setText("Introduzca una letra:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextFieldLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                averiguaPalabra(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldLetra, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcador"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelIntentos.setText("Intentos: 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabelIntentos, gridBagConstraints);

        jLabelAciertos.setText("Aciertos: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabelAciertos, gridBagConstraints);

        jLabelFallos.setText("Fallos: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabelFallos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Muñeco"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabelMuñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emagic/gfx/cabeza.jpeg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabelMuñeco, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabelMuñeco1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel3, gridBagConstraints);

        jMenu1.setText("Juego");

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emagic/gfx/appearance.gif"))); // NOI18N
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickNuevo(evt);
            }
        });
        jMenu1.add(jMenuItemNuevo);
        jMenu1.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emagic/gfx/down.gif"))); // NOI18N
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickNuevo(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItemAcerdaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAcerdaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emagic/gfx/help.gif"))); // NOI18N
        jMenuItemAcerdaDe.setText("Acerca de ");
        jMenuItemAcerdaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickNuevo(evt);
            }
        });
        jMenu2.add(jMenuItemAcerdaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickNuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickNuevo
        // Bucle del juego
        if (evt.getSource() == jMenuItemNuevo) { 
            muñeco = new Muñeco(jLabelMuñeco);
            palabra = new Palabra();
            marcador = new Marcador();
            jLabelAciertos.setText("Aciertos");
            jLabelFallos.setText("Fallos");
            jLabelIntentos.setText("Intentos: 0");
            jLabelPalabra.setText(palabra.getGuiones()); // Poner palabra de juego                        
            jTextFieldLetra.setEnabled(true);
            
        } else if (evt.getSource() == jMenuItemSalir) { 
            System.exit(0);
        } else {
           JOptionPane.showMessageDialog(this, "Juego del Ahorcado 1.0 \n Autora: Elena Martínez Pérez", "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_clickNuevo
    
    private void averiguaPalabra(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_averiguaPalabra
        
        boolean acierto;
        char letra;
        
        letra = jTextFieldLetra.getText().charAt(0);
        acierto = palabra.pruebaLetra(letra);// Pedir letra
        if (acierto) {// Comprobar letra
            marcador.addAcierto(letra);// Si acierto poner acierto
            jLabelAciertos.setText("Aciertos: " + marcador.getListaAciertos());
            jLabelPalabra.setText(palabra.getGuiones());
        } else {
            marcador.addFallos(letra); // Si fallo poner fallo
            jLabelFallos.setText("Fallos: " + marcador.getListaFallos());
            muñeco.cambiaMuñeco(); // Poner muñeco
        }
        marcador.addIntentos();// Aumentar intento
        jLabelIntentos.setText("Intentos: " + marcador.getIntentos());
        
        // Comprobar  no ahorcado o ganador
        if (muñeco.ahorcado()) {
            JOptionPane.showMessageDialog(this, "Lo siento ha sido ahorcado!!!", "Ahorcado", JOptionPane.ERROR_MESSAGE);
            jTextFieldLetra.setEnabled(false); // Deshabilitamos boton
        }
        if (palabra.ganador()) {
            JOptionPane.showMessageDialog(this, "Felicidades ha ganado el juego del ahorcado!!!", "Ahorcado", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldLetra.setEnabled(false); // Deshabilitamos boton
        }
        jTextFieldLetra.setText("");
    }//GEN-LAST:event_averiguaPalabra

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameAhorcado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAciertos;
    private javax.swing.JLabel jLabelFallos;
    private javax.swing.JLabel jLabelIntentos;
    private javax.swing.JLabel jLabelMuñeco;
    private javax.swing.JLabel jLabelMuñeco1;
    private javax.swing.JLabel jLabelPalabra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAcerdaDe;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldLetra;
    // End of variables declaration//GEN-END:variables
}
